### ISSUE TITLE
Can't install on osx sierra

### ISSUE THREAD

**Issue by toejough** [gregjurman/tesserwrap#23]
```
pip install tesserwrap
Collecting tesserwrap
  Downloading tesserwrap-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    ld: library not found for -lcrt1.o
    ld: library not found for -lcrt1.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yp/mhyppj_15z15cl2bf1_cn7jm0000gn/T/pip-build-3opbjwz5/tesserwrap/setup.py", line 45, in <module>
        extra_lib_paths)
      File "/private/var/folders/yp/mhyppj_15z15cl2bf1_cn7jm0000gn/T/pip-build-3opbjwz5/tesserwrap/setup.py", line 30, in find_closest_libname
        "Cannot find Tesseract via ldconfig, confirm it is installed.")
    Exception: Cannot find Tesseract via ldconfig, confirm it is installed.
```

I installed tesseract with brew, and it does appear to be installed:
```
tesseract
Usage:
  tesseract --help | --help-psm | --help-oem | --version
  tesseract --list-langs [--tessdata-dir PATH]
  tesseract --print-parameters [options...] [configfile...]
  tesseract imagename|stdin outputbase|stdout [options...] [configfile...]

OCR options:
  --tessdata-dir PATH   Specify the location of tessdata path.
  --user-words PATH     Specify the location of user words file.
  --user-patterns PATH  Specify the location of user patterns file.
  -l LANG[+LANG]        Specify language(s) used for OCR.
  -c VAR=VALUE          Set value for config variables.
                        Multiple -c arguments are allowed.
  --psm NUM             Specify page segmentation mode.
  --oem NUM             Specify OCR Engine mode.
NOTE: These options must occur before any configfile.
...
```

Some light digging on the internet and uninstalling/reinstalling tesseract have turned up nothing.  Any idea what's going on here?

**Comment by toejough** [comment]
Actually, I've got one sierra host that this is all running fine on.  Trying to figure out what the difference is...

**Comment by toejough** [comment]
ugh.  :man_facepalming: had to manually install the commandline tools package after updating xcode.
